#
# Licensed to Apereo under one or more contributor license
# agreements. See the NOTICE file distributed with this work
# for additional information regarding copyright ownership.
# Apereo licenses this file to you under the Apache License,
# Version 2.0 (the "License"); you may not use this file
# except in compliance with the License.  You may obtain a
# copy of the License at the following location:
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
#

FROM node:5.7.1-slim
RUN npm install -g http-server grunt-cli

RUN apt-get update
RUN apt-get install bzip2

# Add frame
ADD uw-frame-components /build/uw-frame-components
ADD uw-frame-static /build/uw-frame-static
ADD package.json /build
ADD Gruntfile.js /build

# build frame
WORKDIR /build
RUN npm run build-static
RUN cp -r /build/uw-frame-static/target /data

# entry point
ENTRYPOINT ["http-server","/data", "-p","8009"]
